src/model.rs
Added MARKET_LOT_SIZE to Filtertype
See: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#market_lot_size
=> [general/exchange_info] Added MARKET_LOT_SIZE to Filtertype

Cargo.toml, examples/binance_endpoints.rs, examples/binance_futures_endpoints.rs, examples/binance_save_all_trades.rs, examples/binance_websockets.rs, src/account.rs, src/api.rs, src/client.rs, src/errors.rs, src/futures/general.rs, src/futures/model.rs, src/general.rs, src/lib.rs, src/market.rs, src/userstream.rs, src/util.rs, src/websockets.rs
I generated this commit by running `cargo fix --edition`, `cargo fix --edition-idioms`, then fixing all clippy errors and warnings manually.
Fixes #42
=> Update crate to Rust 2018

src/account.rs, src/model.rs
https://github.com/wisespace-io/binance-rs/issues/45
=> Add MarketOrder refactor market_buy/market_sell request

Cargo.toml, src/account.rs
As defined here: https://binance-docs.github.io/apidocs/spot/en/#cancel-all-open-orders-on-a-symbol-trade
=> Add cancel all orders for Spot

src/account.rs
Usage:
```
match account.custom_order(PAIR, 9999, 0.0123, "SELL", "LIMIT", "IOC") {
Ok(answer) => println!("{:?}", answer),
Err(e) => println!("Error: {}", e),
}
```
Also fixes https://github.com/wisespace-io/binance-rs/issues/62
=> Add support for custom orders

README.md
fix api link
remove not needed external crate statements
add example for cancel all orders
improve error print formatting
=> Attempt to improve readme:

src/api.rs, src/config.rs
Added a field to the `Config` struct to set a default recv_window.
=> Make recv_window flexible

Cargo.toml, src/account.rs, src/api.rs, src/client.rs, src/futures/general.rs, src/futures/market.rs, src/general.rs, src/market.rs, src/userstream.rs
In this PR I am including these functions:
- stop_limit_sell_order
- test_stop_limit_sell_order
- stop_limit_buy_order
- test_stop_limit_buy_order
It also include more concise types like:
- OrderType
- Limit
- Market
- StopLossLimit
- OrderSide
- Buy
- Sell
@dorak88783 Could you please review?
=> Add Stop Limit

src/model.rs
=> fix spot depth event

src/errors.rs, src/futures/market.rs, src/market.rs, src/model.rs, tests/market_tests.rs
Regarding #136, change the types of KlineSummary.
=> Unify kline data type

benches/websocket_benchmark.rs, examples/binance_endpoints.rs, examples/binance_websockets.rs, src/account.rs, src/api.rs, src/client.rs, src/config.rs, src/futures/account.rs, src/futures/market.rs, src/futures/mod.rs, src/futures/model.rs, src/lib.rs, src/market.rs, src/model.rs, src/savings.rs, src/userstream.rs, src/util.rs, src/websockets.rs, tests/account_tests.rs, tests/futures_account_tests.rs, tests/general_tests.rs, tests/market_tests.rs, tests/util_tests.rs
@wisespace-io This PR simply reformat the code with `rustfmt`.
=> Reformat with rustfmt

src/model.rs, src/websockets.rs
AccountUpdate event never fired, now the balance updates can be caught
=> added BalanceUpdate event support

src/model.rs
```
Error("unknown variant `TRAILING_DELTA`, expected one of `PRICE_FILTER`, `PERCENT_PRICE`, `LOT_SIZE`, `MIN_NOTIONAL`, `ICEBERG_PARTS`, `MAX_NUM_ORDERS`, `MAX_NUM_ALGO_ORDERS`, `MAX_NUM_ICEBERG_ORDERS`, `MAX_POSITION`, `MARKET_LOT_SIZE`", line: 0, column: 0)
```
=> Added new type filter in symbol

examples/binance_websockets.rs, src/config.rs, src/futures/model.rs, src/futures/websockets.rs, src/model.rs, src/websockets.rs
updated API added code in accordance with the changes
[https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update](url)
=> fix User Stream AccountUpdateEvent 

src/account.rs, src/config.rs, src/futures/account.rs
use built-in traits where appropriate
=> use built-in traits

examples/binance_futures_websockets.rs, src/futures/websockets.rs, src/websockets.rs
unfortunately this PR is unnecessarily noisy due to autoformatting making changes outside the scope of the PR.
I'll create a separate PR for checking the formatting in CI, and if that is merged first it will clean this PR (and future PRs) up.
=> remove needless pass by value

Cargo.toml, src/client.rs
these depend on each other, so need to be updated together
=> update sha2 and hmac deps

.github/workflows/rust.yml, benches/websocket_benchmark.rs
have attempted to fix the benchmarks.
I'm not sure how these are supposed to work, so this should be reviewed carefully @wisespace-io
=> fix benchmarks

src/futures/websockets.rs, src/model.rs, src/websockets.rs
Binance has added additional streaming options:
https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-rolling-window-statistics-streams
I'm new to Rust (and contributing at all), so please excuse if something wrong, I'm ready to fix
=> add rolling window statistics streams

src/account.rs, src/util.rs
- Added trade_history_from.
- Added trade_history_from_to.
=> Extended trade history parsing.

src/model.rs
- relates to https://github.com/ccxt/binance-rs/issues/250
=> fix(futures): exchangeInfo type

src/model.rs
- relates to https://github.com/ccxt/binance-rs/issues/270
=> fix(client): add maxNumOrderAmends and MAX_NUM_ORDER_LISTS to Filters
