ccxt/binance-rs

src/lib.rs
It is poor practice to expose a private struct as a return for a public interface, especially for errors.
It works only on a technicality, as your examples use a match instead of the more accepted method of deriving a new error type with the From trait. With the library currently there is no way to adopt this trait, making it useless for libraries that wish to adapt and return their own errors, or client code that wishes to make use of the try ? operator.
=> errors module should be public to allow for error wrapping

Cargo.toml, src/general.rs, src/model.rs
Support for the [exchange information](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information) endpoint. This is most useful for obtaining symbol metadata (ie the base vs quote).
=> Add Exchange Information support

src/model.rs
When requesting exchange informations, a part of the data were not included in the struct which this PR intends to fix.
Now:
```rust
Symbol {
symbol: "ZECUSDC",
status: "TRADING",
base_asset: "ZEC",
base_asset_precision: 8,
quote_asset: "USDC",
quote_precision: 8,
order_types: [
"LIMIT",
"LIMIT_MAKER",
"MARKET",
"STOP_LOSS_LIMIT",
"TAKE_PROFIT_LIMIT"
],
iceberg_allowed: true,
is_spot_trading_allowed: true,
is_margin_trading_allowed: false,
filters: [
PriceFilter {
min_price: "0.01000000",
max_price: "10000000.00000000",
tick_size: "0.01000000"
},
PercentPrice {
multiplier_up: "10",
multiplier_down: "0.1",
avg_price_mins: 5.0
},
LotSize {
min_qty: "0.00001000",
max_qty: "10000000.00000000",
step_size: "0.00001000"
},
MinNotional {
min_notional: "10.00000000",
apply_to_market: true, …
```
=> can deserialize Symbol's filters

src/client.rs
fix that error 
```
thread 'main' panicked at 'invalid header name'
[...]
6: http::header::name::parse_hdr::{{closure}}
at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.16/src/header/name.rs:1660
7: binance::client::Client::build_headers
at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/binance-0.3.2/src/client.rs:127
8: binance::client::Client::new::{{closure}}
at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/binance-0.3.2/src/client.rs:41
9: binance::account::Account::limit_buy
at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/binance-0.3.2/src/account.rs:115
```
since `reqwest` has been updated to 0.9 hence `http 1.1.16` which only allows lowercase header's name cf. https://docs.rs/http/0.1.16/http/header/struct.HeaderName.html#method.f …
=> panic api_key fixed

src/client.rs
Until now, we couldn't see the content of the Bad Request.
=> shows Binance's reponse code & msg on Bad Request

src/client.rs, src/errors.rs
This allows to be more specific when managing errors and take action accordingly.
```rust
use binance::errors::ErrorKind as BinanceLibErrorKind;
[...]
Err(err) => {
println!("Can't put an order!");
match err.0 {
BinanceLibErrorKind::BinanceError(code, msg, response) => match code {
-1013_i16 => println!("Filter failure: LOT_SIZE!"),
-2010_i16 => println!("Funds insufficient! {}", msg),
_ => println!("Non-catched code {}: {}", code, msg),
},
BinanceLibErrorKind::Msg(msg) => {
println!("Binancelib error msg: {}", msg)
}
_ => println!("Other errors: {}.", err.0),
};
}
```
=> handle binance's errors with more precision

examples/src/binance_save_all_trades.rs, examples/src/binance_websockets.rs, src/websockets.rs
Moves websocket API so the delegates are borrowed.  This allows the
parent to do things like, have a single unified struct implement
all the API delegate interfaces and share the same struct to each
API delegate.  The delegate, for example, could own the WebSockets
struct and mutate members or even shutdown the websocket within a
callback from the websocket API.
=> Change websocket API to use delegate with proper lifetime management

examples/src/binance_save_all_trades.rs, examples/src/binance_websockets.rs, src/websockets.rs
Instead of using a delegate-style system, this patch moves to use
a callback-event-like system.  This simplifies the code for the
consumer and implementation.  This will allow multi-threaded
systems much easier by giving a single point where a consumer could
plum the calls out of the websocket API up to another thread.
=> Simplify the websocket implementation to use a single callback

src/model.rs
The first_trade_id and last_trade_id are declared as u64, but the binance API sometimes returns -1, causing a panic. This changes those types to i64 to accommodate the possible negative values.
=> Fixing websocket DayTicker failing on unknown trade id's

examples/binance_save_all_trades.rs, examples/binance_websockets.rs, src/websockets.rs
If there's a better/established way of doing this, let me know.
Currently the WebSockets callback doesn't have any return value. The event_loop() returns a Result, but it's limited to errors that might arise strictly from the websockets. Any problems within the callback is limited to a panic. Allowing the callback to return its own Result, that would be bubbled up through to the return value of the event_loop() helps write smarter error handling around websocket events.
This changes the function signature of the callback arg, thus breaking the current API. I've gone and updated the examples, but consumers will not be able to simply upgrade the package version without modifications themselves
=> Changing websocket callback to return a Result

src/account.rs, src/model.rs
I've added support only for `limit_buy` orders.
I'd like you to review the code, and if you're ok with the implementation I can add support for all the remaining orders.
=> Add function `account::Account::test_limit_buy`.

src/account.rs, src/model.rs
Not sure if `Account::order_status` is useful at all, but I have included it for the sake of completeness.
=> Implement all remaining orders for the test endpoint

src/model.rs, src/websockets.rs
This should work for both `<symbol>@bookTicker` and `!bookTicker` streams. 
It's not the most elegant solution but seeing as there's no `eventType` in the payload the easiest way was to validate the schema.
=> Add support for BookTickerEvent

src/api.rs
The endpoint is actually `api.binance.com` (https://binance-docs.github.io/apidocs/spot/en/#general-info). It's surprising that `www.binance.com` even works, but just in case Binance deprecates calling the API from `www.binance.com`, let's update it.
=> Endpoint update

src/websockets.rs
Initially implemented on https://github.com/0x53A/binance-rs/commit/ed9342f5770d62a890829fa83178af57d5be09b0 but then adapted to fit current version. Works fine on [gabriel-milan/btrader](https://github.com/gabriel-milan/btrader).
Refers to https://github.com/wisespace-io/binance-rs/issues/15 and https://github.com/wisespace-io/binance-rs/issues/48 (and probably https://github.com/wisespace-io/binance-rs/issues/56).
https://github.com/wisespace-io/binance-rs/issues/15 mentions that it works just by using the current implementation, but I had few issues while trying with around 780 symbols. Official API reference: https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#general-wss-information
=> Add support to combined streams

src/account.rs
Note that canceling OCO orders still might not work.
Fix for https://github.com/wisespace-io/binance-rs/issues/66.
=> Fix return type for cancel all orders. 

src/model.rs, src/websockets.rs
Added the actual '<symbol>@trade' support. Copied docs for AggrTrade and Trade.
Renamed TradesEvent into AggrTradesEvent which is breaking change but makes it more readable.
=> singular-trade

src/market.rs, src/model.rs
The Binance API makes the symbol parameter optional in 24hr ticker price statistics (https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#24hr-ticker-price-change-statistics), to enable downloading of all symbol statistics in one go. This is what this function provides.
=> New function "get_all_24h_price_stats"

src/websockets.rs
Maybe there is a good reason this wasn't enabled, but it was convenient for me while debugging.
=> Add derive-debug and other useful derives on the WebsocketEvent

.github/workflows/rust.yml
Enable a simple github action flow, including clippy.
I didn't remove the existing travis config, so I guess they will run both now.
=> Enable github action

src/client.rs
I didn't see this in my review of @ppamorim 's PR, but found it while testing.
Using `{:?}` will put extra quotes around the printed string, which isn't correct.
=> Fix critical typo in building request body

src/model.rs
For Futures https://fapi.binance.com/fapi/v1/exchangeInfo response is
{"filterType":"MIN_NOTIONAL","notional":"5"}
For Spot https://api.binance.com/api/v1/exchangeInfo response is
{"filterType":"MIN_NOTIONAL","minNotional":"0.00010000","applyToMarket":true,"avgPriceMins":5}
=> Fix MinNotional filter.

src/api.rs, tests/market_tests.rs
Added "r" letter at the end of api address. With this fix, it is not giving 404 error anymore.
=> Fixing typo for Spot::Ticker24hr in api.rs

src/model.rs
This field is required to be checked when one wants to have a local order book.
=> Add pu field to DepthOrderBookEvent

src/config.rs
if the testnet config is used, we get the following error as we have repeated `api` in the URL:
```
2021-05-22 10:15:58,765 DEBUG [reqwest::async_impl::client] response '404 Not Found' for https://testnet.binance.vision/api/api/v3/account?recvWindow=5000&timestamp=1621671357714...
```
=> fix: fix testenet api endpoints

src/websockets.rs
All `connect` functions receive `subscription`. However, currently there is no way to create `WebSockets` with temporary config and subscription even though they are not needed to exist for the whole lifetime of `WebSockets`.
=> Remove WebSockets::subscription

src/account.rs, tests/account_tests.rs
add the possibility to provide a client's order ID in the custom mode
=> feat: add client id for custom order

src/futures/account.rs
Apparently Binance does not allow the timeInForce parameter for market orders (in hindsight it does not make much sense to have it there anyway), so I removed it.
The current implementation will always error with:
`Error(BinanceError(BinanceContentError { code: -1106, msg: "Parameter \'timeInForce\' sent when not required.", extra: {} }), State { next_error: None, backtrace: InternalBacktrace }`
This time I actually tested it and it works now.
=> Fix bug in futures market_buy and market_sell

src/model.rs
Binance is using "INF" as a string for infinity. For example, when calling change_initial_leverage with a leverage of 1, the response will contain a max_notional_value of "INF".
The current version fails with a decode error, so I added a check to the decoder.
=> Change string_or_float to accept INF

examples/binance_futures_websockets.rs, src/futures/mod.rs, src/futures/websockets.rs, src/model.rs, src/websockets.rs
Add support for future websockets: implemented the USD-M and COIN-M endpoints; vanilla options are not implemented yet.
There is an example that shows their working, but it depends on the uptime of the binance servers, so I didn't make this into a real test. Real tests (with a mocked) server would be nice. Also documentation is not 100% complete.
=> Add futures websockets

src/futures/market.rs
Consistent with the get_custom_depth function signature for the spot api.
=> added futures get_custom_depth function

src/model.rs
`number_of_trades` in `KlineSummary` is `i64` while in `Kline` is `i32`. @wisespace-io
=> Change types in Kline from i32 to i64

src/model.rs
> Error on getting exchange info: error decoding response body: unknown variant `PERCENT_PRICE_BY_SIDE`, expected one of `PRICE_FILTER`, `PERCENT_PRICE`, `LOT_SIZE`, `MIN_NOTIONAL`, `ICEBERG_PARTS`, `MAX_NUM_ORDERS`, `MAX_NUM_ALGO_ORDERS`, `MAX_NUM_ICEBERG_ORDERS`, `MAX_POSITION`, `MARKET_LOT_SIZE`, `TRAILING_DELTA` at line 1 column 631893
https://binance-docs.github.io/apidocs/spot/en/#filters
=> Add new filter types: NOTIONAL and PERCENT_PRICE_BY_SIDE

src/futures/account.rs
Currently, the TimeInForce enum used to place futures orders is written for spot, which lacks a GTX type.
A new enum is created for futures in this commit.
I have tested it and it works fine for placing orders.
=> support TimeInForce's GTX type in futures orders

Cargo.toml, src/config.rs, src/futures/general.rs, src/websockets.rs, tests/account_tests.rs, tests/futures_account_tests.rs, tests/futures_general_tests.rs, tests/futures_market_test.rs, tests/general_tests.rs, tests/market_tests.rs
1. The wss endpoint with 9443 port seems to have issue according to #123. By simply adjusting the default endpoint the problem can be fixed.
2. The mock module has deprecated since mockito 1.0.0. Upgraded the dependencies and affected test module. Some other dependencies are also safely upgraded.
3. FuturesGeneral::ping() doesn't work and since there lacks a test for that, this issue has not been discovered. Added a test module for that and fixed the function.
I'm a Rust beginner and tried my best to make this little contribution.
=> Some minor fixes: default wss endpoint, dependencies upgrade and futures general endpoint ping
